#!/bin/sh
# Lets wait a bit for things to stabilize after boot
#sleep 60
#CONFIG=/mnt/mmc0/device_info/setting.ini
CONFIG=./setting.ini
#WPA=/tmp/wpa.conf
WPA=./wpa.conf
AWK=/usr/bin/awk
# Code to start a shell if needed for debugging
#if [ false ]; then
#  cp /mnt/mmc0/bdtest/telnetd-static /tmp/telnetd
#  cd /tmp
#  ./telnetd -p 7335 -l /bin/sh &
#fi

# This variable test to see if we are requesting a WPA ENT config
WPANEEDED=`/bin/cat ${CONFIG}|/bin/grep NET_WIFI_PASSWORD_00|/bin/grep WPA-PEAP-MSCHAPV2`
# This variable will see if we already have a proper config file that support WPA ENT.
WPAWORKING=`/bin/cat ${WPA}|/bin/grep eap=PEAP`
echo wpa needed = ${WPANEEDED}
echo wpa working = ${WPAWORKING}
#Check to see if the settings want WPA-ENT
if [ "${WPANEEDED}" != "" ]; then
  echo "WPA ENT is needed..."
  #now lets check to see if the existing file already has it set
  if [ -z "${WPAWORKING}" ]; then
    # Our settings are not correct, lets fix
    echo "WPA is NOT applied..."
    SSID=`/bin/cat ${CONFIG}|/bin/grep NET_WIFI_SSID_00|${AWK} -F\= ' { print $2 } '`
    IDENTITY=`/bin/cat ${CONFIG}|/bin/grep NET_WIFI_PASSWORD_00|${AWK} -F\; ' { print $2 } '`
    PASSWORD=`/bin/cat ${CONFIG}|/bin/grep NET_WIFI_PASSWORD_00|${AWK} -F\; ' { print $3 } '`
    echo SSID=${SSID} IDEDNTITY=${IDENTITY} PASS=${PASSWORD}
    /bin/cat << EOF > ./wpa-final.conf
ctrl_interface=DIR=/var/run/wpa_supplicant GROUP=netdev
update_config=1
network={
    ssid="${SSID}"
    #psk="WPA-PEAP-MSCHAPV2;${IDENTITY};${PASSWORD}"
    scan_ssid=1
    key_mgmt=WPA-EAP
    eap=PEAP
    identity="${IDENTITY}"
    password="${PASSWORD}"
    #ca_cert="/etc/ssl/certs/ca-certificates.crt"
    phase1="peaplabel=0"
    phase2="auth=MSCHAPV2"
}
EOF
  fi
fi

#
